# Загрузка данных анкет и проведение МАИ, анализ полученных результатов
Данные: заполненные анкеты экспертов (таблицы Excel)

In [1]:
import re
import numpy as np
import pandas as pd
import scipy as sp
import matplotlib.pyplot as plt
from random import randint

In [2]:
df = pd.read_excel(r'C:\Users\user\инциденты\Экс14.xlsx')
df.head()

,Тип нарушения,Документация,Экспертиза промышленной безопасности,Готовность к ликвидации последствий аварий и инцидентов,Оформление информационными знаками и знаками безопасности,Содержание объектов и оборудования,Охранные зоны (ОЗ),Организация рабочего процесса и безопасности персонала
0,Документация,1.000000,9,7.000000,3.0,9,5,5
1,Экспертиза промышленной безопасности,0.111111,1,1.000000,1.0,1,1,1
2,Готовность к ликвидации последствий аварий и и...,0.142857,1,1.000000,3.0,1,1,1
3,Оформление информационными знаками и знаками б...,0.333333,1,0.333333,1.0,1,3,5
4,Содержание объектов и оборудования,0.111111,1,1.000000,1.0,1,1,1

In [3]:
print('Число строк и столбцов в наборе данных:\n', df.shape)

Число строк и столбцов в наборе данных:
 (7, 8)

In [4]:
# типы столбцов 
df.dtypes

Тип нарушения                                                 object
Документация                                                 float64
Экспертиза промышленной безопасности                           int64
Готовность к ликвидации последствий аварий и инцидентов      float64
Оформление информационными знаками и знаками безопасности    float64
Содержание объектов и оборудования                             int64
Охранные зоны (ОЗ)                                             int64
Организация рабочего процесса и безопасности персонала         int64
dtype: object

In [5]:
#удаление столбца типа object для дальнейшей работы с фреймом 
df.pop('Тип нарушения') 
print(df)

   Документация   Экспертиза промышленной безопасности  \
0       1.000000                                     9
1       0.111111                                     1
2       0.142857                                     1
3       0.333333                                     1
4       0.111111                                     1
5       0.200000                                     1
6       0.200000                                     1

   Готовность к ликвидации последствий аварий и инцидентов  \
0                                           7.000000
1                                           1.000000
2                                           1.000000
3                                           0.333333
4                                           1.000000
5                                           1.000000
6                                           1.000000

   Оформление информационными знаками и знаками безопасности  \
0                                           3.000000
1                                           1.000000
2                                           3.000000
3                                           1.000000
4                                           1.000000
5                                           0.333333
6                                           0.200000

   Содержание объектов и оборудования   Охранные зоны (ОЗ)  \
0                                    9                   5
1                                    1                   1
2                                    1                   1
3                                    1                   3
4                                    1                   1
5                                    1                   1
6                                    1                   1

   Организация рабочего процесса и безопасности персонала
0                                                  5
1                                                  1
2                                                  1
3                                                  5
4                                                  1
5                                                  1
6                                                  1

In [6]:
# типы столбцов 
df.dtypes

Документация                                                 float64
Экспертиза промышленной безопасности                           int64
Готовность к ликвидации последствий аварий и инцидентов      float64
Оформление информационными знаками и знаками безопасности    float64
Содержание объектов и оборудования                             int64
Охранные зоны (ОЗ)                                             int64
Организация рабочего процесса и безопасности персонала         int64
dtype: object

In [7]:
# также меням тип данных Документации
df['Документация '] = df['Документация '].astype(float)

In [8]:
df.loc[:, df.columns[df.dtypes == 'float64']].head(7)

,Документация,Готовность к ликвидации последствий аварий и инцидентов,Оформление информационными знаками и знаками безопасности
0,1.000000,7.000000,3.000000
1,0.111111,1.000000,1.000000
2,0.142857,1.000000,3.000000
3,0.333333,0.333333,1.000000
4,0.111111,1.000000,1.000000
5,0.200000,1.000000,0.333333
6,0.200000,1.000000,0.200000

In [9]:
DF_1=df[:].copy()

In [10]:
#Найдем сумму всех столбцов, для того чтобы в дальнейшем пересчитать полученные значения
df.sum ()

Документация                                                  2.098413
Экспертиза промышленной безопасности                         15.000000
Готовность к ликвидации последствий аварий и инцидентов      12.333333
Оформление информационными знаками и знаками безопасности     9.533333
Содержание объектов и оборудования                           15.000000
Охранные зоны (ОЗ)                                           13.000000
Организация рабочего процесса и безопасности персонала       15.000000
dtype: float64

In [11]:
# Считаем значения для нашей матрицы, путем деления каждого значения в столбце на сумму столбца
df['new_Документация'] = df['Документация '].astype(float).div(df['Документация '].sum())
df['new_Экспертиза'] = df['Экспертиза промышленной безопасности'].astype(float).div(df['Экспертиза промышленной безопасности'].sum())
df['new_Готовность'] = df['Готовность к ликвидации последствий аварий и инцидентов'].astype(float).div(df['Готовность к ликвидации последствий аварий и инцидентов'].sum())
df['new_Оформление'] = df['Оформление информационными знаками и знаками безопасности'].astype(float).div(df['Оформление информационными знаками и знаками безопасности'].sum())
df['new_Содержание'] = df['Содержание объектов и оборудования '].astype(float).div(df['Содержание объектов и оборудования '].sum())
df['new_ОЗ'] = df['Охранные зоны (ОЗ)'].astype(float).div(df['Охранные зоны (ОЗ)'].sum())
df['new_Организация'] = df['Организация рабочего процесса и безопасности персонала'].astype(float).div(df['Организация рабочего процесса и безопасности персонала'].sum())

In [12]:
df.head()

,Документация,Экспертиза промышленной безопасности,Готовность к ликвидации последствий аварий и инцидентов,Оформление информационными знаками и знаками безопасности,Содержание объектов и оборудования,Охранные зоны (ОЗ),Организация рабочего процесса и безопасности персонала,new_Документация,new_Экспертиза,new_Готовность,new_Оформление,new_Содержание,new_ОЗ,new_Организация
0,1.000000,9,7.000000,3.0,9,5,5,0.476551,0.600000,0.567568,0.314685,0.600000,0.384615,0.333333
1,0.111111,1,1.000000,1.0,1,1,1,0.052950,0.066667,0.081081,0.104895,0.066667,0.076923,0.066667
2,0.142857,1,1.000000,3.0,1,1,1,0.068079,0.066667,0.081081,0.314685,0.066667,0.076923,0.066667
3,0.333333,1,0.333333,1.0,1,3,5,0.158850,0.066667,0.027027,0.104895,0.066667,0.230769,0.333333
4,0.111111,1,1.000000,1.0,1,1,1,0.052950,0.066667,0.081081,0.104895,0.066667,0.076923,0.066667

In [13]:
# Получили новую таблицу теперь отделим значения нашей матрицы от основной таблицы
df_new = df[['new_Документация', 'new_Экспертиза', 'new_Готовность', 'new_Оформление', 'new_Содержание', 'new_ОЗ', 'new_Организация']]
df_new

,new_Документация,new_Экспертиза,new_Готовность,new_Оформление,new_Содержание,new_ОЗ,new_Организация
0,0.476551,0.600000,0.567568,0.314685,0.600000,0.384615,0.333333
1,0.052950,0.066667,0.081081,0.104895,0.066667,0.076923,0.066667
2,0.068079,0.066667,0.081081,0.314685,0.066667,0.076923,0.066667
3,0.158850,0.066667,0.027027,0.104895,0.066667,0.230769,0.333333
4,0.052950,0.066667,0.081081,0.104895,0.066667,0.076923,0.066667
5,0.095310,0.066667,0.081081,0.034965,0.066667,0.076923,0.066667
6,0.095310,0.066667,0.081081,0.020979,0.066667,0.076923,0.066667

In [14]:
#Вычислим средние значение по строке и запишем полученный результот в mean
df_new['mean'] = df_new.mean(axis=1)
df_new.head()

C:\Users\user\anaconda3\envs\envpy3.5\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,new_Документация,new_Экспертиза,new_Готовность,new_Оформление,new_Содержание,new_ОЗ,new_Организация,mean
0,0.476551,0.600000,0.567568,0.314685,0.600000,0.384615,0.333333,0.468107
1,0.052950,0.066667,0.081081,0.104895,0.066667,0.076923,0.066667,0.073693
2,0.068079,0.066667,0.081081,0.314685,0.066667,0.076923,0.066667,0.105824
3,0.158850,0.066667,0.027027,0.104895,0.066667,0.230769,0.333333,0.141173
4,0.052950,0.066667,0.081081,0.104895,0.066667,0.076923,0.066667,0.073693

In [15]:
#проверка, среднее значение в сумме должно быть равно 1
df_new['mean'].sum()

1.0

In [16]:
# Далее проведем проверку на согласованность, 
#для этого создадим из нашей полученной выше таблицы матрицы для дальнейшего их перемножения
df_new8 =df_new['mean']

# удаляем из нашей таблицы значениея столбцы mean
#df_new.pop('mean')

df_new1 =DF_1.loc[0]

df_new2 =DF_1.loc[1]

df_new3 =DF_1.loc[2]

df_new4 =DF_1.loc[3]

df_new5 =DF_1.loc[4]

df_new6 =DF_1.loc[5]

df_new7 =DF_1.loc[6]

In [17]:
#Проверка на согласованность
res1 = np.dot(df_new1,df_new8)
print(res1)
res2 = np.dot(df_new2,df_new8)
print(res2)
res3 = np.dot(df_new3,df_new8)
print(res3)
res4 = np.dot(df_new4,df_new8)
print(res4)
res5 = np.dot(df_new5,df_new8)
print(res5)
res6 = np.dot(df_new6,df_new8)
print(res6)
res7 = np.dot(df_new7,df_new8)
print(res7)

3.6464150506105013
0.5839044721881971
0.8811102429089847
1.0279121384504024
0.5839044721881971
0.5313989529561128
0.5125759386005668

In [18]:
sum_new = res1 + res2 + res3 + res4 + res5 + res6 + res7
print(sum_new)

7.767221267902962

In [19]:
# Вычислем значения CI, RI, CR
CI = (sum_new - 7)/(7-1)
print(CI)
RI = (1.98*(7-2))/7
print(RI)
CR = CI/RI
print(CR)

0.12787021131716036
1.4142857142857144
0.09041328072930531

In [20]:
# Получилось, что значение CR=0.09, что меньше 0,1 значит матрицу можно считать согласованной
# Проделаем аналогичные действия с другими экспертами